#!/usr/bin/env perl
use warnings;
use strict;

use FindBin qw($Bin);
use lib "$Bin/../../lib";

use Daemon::Control;

my $name = 'email';

my $logdir = $ENV{SMM_LOG_DIR} || '/tmp';

$0 = "daemon $name";

my $stderr = "/$logdir/$name.error.log";
print "std-error $stderr\n";
Daemon::Control->new(
    {
        name      => "$name daemon control",
        lsb_start => '$syslog $remote_fs',
        lsb_stop  => '$syslog',
        lsb_sdesc => "Daemon Control $name",
        lsb_desc  => "Daemon Control $name",

        fork        => 2,
        program     => "$Bin/bin/$name.pl",

        pid_file    => "/$logdir/$name.pid",
        stderr_file => $stderr,
        stdout_file => "/$logdir/$name.log",

        kill_timeout => 30,
    }
)->run;

