---
abstract: 'Catalyst based application'
author:
  - 'Renato CRON'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Deep: 0
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SMM
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Component::InstancePerContext: 0
  Catalyst::Controller::REST: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Assets: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::Authorization::Roles: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::I18N::DBI: 0
  Catalyst::Plugin::Params::Nested: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode::Encoding: 0
  Catalyst::Runtime: '5.90010'
  Catalyst::TraitFor::Controller::DBIC::DoesPaging: 0
  Catalyst::View::TT: 0
  Config::General: 0
  Crypt::PasswdMD5: 0
  DBD::Pg: 0
  DBIx::Class::PassphraseColumn: 0
  DBIx::Class::TimeStamp: 0
  Data::Diver: 0
  Data::Manager: 0
  Data::Printer: 0
  DateTime::Duration: 0
  DateTime::Format::Duration: 0
  DateTime::Format::Excel: 0
  DateTime::Format::Pg: 0
  DateTimeX::Easy: 0
  Digest::MD5: 0
  Email::MIME: 0
  Email::Sender: 0
  Email::Sender::Simple: 0
  Email::Sender::Transport::SMTP::TLS: 0
  FindBin: 0
  Geo::Coder::Google: 0
  I18N::AcceptLanguage: 0
  JSON: 0
  JSON::XS: 0
  List::MoreUtils: 0
  Math::Expression::Evaluator: 0
  Moose: 0
  MooseX::Traits: 0
  MooseX::Types::Email: 0
  Spreadsheet::ParseExcel::Stream: 0
  Spreadsheet::WriteExcel: 0
  Spreadsheet::XLSX: 0
  Statistics::Descriptive: 0
  String::Random: 0
  Template: 0
  Text2URI: 0
  Text::CSV_XS: 0
  Text::Iconv: 0
  XML::Simple: 0
  namespace::autoclean: 0
version: '0.01'
